# Generated by Django 6.0.3 on 2026-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_preferred_time_habit_weekly_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='weekly_day',
        ),
        migrations.AddField(
            model_name='habit',
            name='weekly_days',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
