# Generated by Django 6.0.3 on 2026-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
