# Generated by Django 6.0.3 on 2026-03-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category_alter_task_owner_alter_task_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('personal', 'Personal'), ('health', 'Health'), ('university', 'University'), ('business', 'Business'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
